DROP TABLE task_definition IF EXISTS;
CREATE TABLE task_definition (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL
);

DROP TABLE task_definition_mirror IF EXISTS;
CREATE TABLE task_definition_mirror (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL
);

INSERT INTO task_definition (name, description) VALUES ('Task 1', 'Description');